import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col dark:bg-black">
       <header
          className="
            fixed left-3 right-3 top-3 z-50
            px-4 py-3
            flex items-center
            rounded-xl
            border border-white/20
            bg-black/65
            backdrop-blur-xl
            shadow-[0_0_24px_rgba(255,255,255,0.10),inset_0_1px_0_rgba(255,255,255,0.30)]
            sm:left-5 sm:right-5 sm:top-5 sm:h-14 sm:px-6 sm:py-0
          "
        >
            <nav className="flex w-full flex-wrap items-center justify-between gap-3 text-sm text-white sm:h-full sm:flex-nowrap">
              <div className="flex min-w-0 items-center gap-3">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-white/25 text-lg">
                  +
                </span>
                <span className="truncate font-medium tracking-[0.18em]">OLYMPUS DOMAIN</span>
              </div>

              <div className="order-3 flex w-full items-center justify-center gap-4 text-white/80 sm:order-none sm:w-auto sm:gap-6">
                <button type="button" className="flex items-center gap-2">
                  <span className="h-2 w-2 rounded-full bg-green-400" />
                  Athena
                </button>
                <button type="button" className="flex items-center gap-2">
                  <span className="h-2 w-2 rounded-full bg-amber-400" />
                  Hephaestus
                </button>
                <button type="button" className="hidden rounded-full border border-white/20 px-3 py-1 text-white/70 sm:block">
                  Add agent
                </button>
              </div>

              <div className="flex shrink-0 items-center gap-3 text-white/80 sm:gap-4">
                <span className="hidden items-center gap-2 text-xs tracking-[0.14em] sm:flex">
                  LOCAL · SECURE
                  <span className="h-2 w-2 rounded-full bg-green-400" />
                </span>
                <button type="button" className="h-8 w-8 rounded-full border border-white/20">
                  JB
                </button>
              </div>
            </nav>
        </header>

        <main className="flex-1 bg-black p-6 text-white">{children}</main>
      </body>
    </html>
  );
}
